---
title: "Chapter 0. Preface"
format:
  html: default
  pdf: default
---


## Introduction

Hi! I'm Kevinouio or Kevin Ho.


I'm an undergraduate studing Mathematics and Computer Science. You might be wondering, "Hey is this guy a quant or a wanna be quant or something?" or "This guy must be very smart or somthing". Well I'll tell you what, I'm just a wanna be who just wants to learn about finance. I personally have no idea about anything about finance when it comes to investing, trading, or even quantatative finance. 

## What is this website?

So this website is just myself teaching my topics of finance in long horizing investing, quant topics, and other finance stuff that I don't really understand yet. So bare with me if any of the information feels repetive or boring. I plan and am going to be writing this website with this general structure in mind being:

1. Introduction to the topic
2. Some general verbage and jargon that relates to the topic
3. Code along with the explanations of the method
4. Sometimes an interactive demostration of the method. 

Now for the stucture of the whole textbook will be as follows. 

1. Foundations
2. Long Horizon Investing
3. Systematic Trading
4. Event Driven Relative Value
5. Derivatives Volatitly
6. Microstructure Execution
7. Discretionary Hybrid
8. Synthesis
9. Appendix


The first chapter mainly covers the foundations knowledge before a person should go over before they actually start learning how investing works and before creating their algorithms. Example I personally don't really know much about Volatitly or anything about it and I for sure shouldn't really mess with it until I properly can explain it correctly. This Part of the Website will just go over all of the Jargon though so if you are already comfortable with that, I would skip it I would assume (idk yet about how much is needed from this chapter). So 

The second chapter more goes onto the topic of how to predict the long horizon movement of a given market. (I really only know long horizon from learning about Reinforcement Learning so idk much)

NOTE: WRITE THE REST OF THESE CHAPTERS DESCRIPTION WHEN I FINISH EACH CHAPTERS



## How can I contact you? 

Well I would suggest emailing me or contacting me from my personal website at kevinouio.com. If there is anything that is wrong with anything that I had put into this website that you believe that I should change, please issue a pull request or an issue on the github for this project. All suggestions to how i should approach this is appreciated.


## Why are you doing this? 
 
So my reason for writing this full textbook is out of pure want to learn how I can apply my own knowledge in mathematics, statistics, and computer science in finance. Now I am currently a junior writing this full website in college with no internships or even research ready for the summer so this is just a side project that I want to do. I've feel very behind when it comes to this topic relative to my peers that I meet at hackathons or even research conferences that I go to. This notebook is just a way for me to compensate for that tbh. (sorry about all the yapping btw this is my first time even writing something of the sorts)

I also just want to learn a more algorithmic way to invest rather than relying on just ETFs or other sites or banks that just invest my money for me. I don't want to be waiting 10 years down the line of me putting just 200$ of my money investing every month into a bank. That just in theory feels inefficent. So this is just my way of learning the full systems and the ins and outs of investing and how the Hedge funds do their stuff. 

I also want to develop my 

## Closing Thoughts

Now I want to give thanks to my friends for pushing me to being the most productive person that I try to be even though most of the time, I'm just thinking or not acting on anything. I hope me creating this project inspires you to also do something similar. Also I might end up writing this as if it is a math textbook so sorry in advance for the math formality that I might include in my definitions of words and etc. 


SOOOOO with that being said, I welcome you to my first "textbook" where i provide my own understanding of the topics of finance using math and computer science concepts. 

